# Generated by Django 4.2.3 on 2023-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adver', '0002_adver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adver',
            name='image',
            field=models.ImageField(default='', upload_to='mysite/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
